module.exports.productDataSourceMapping = {
    name : "nameMedicinalProduct",
    gtin : "productCode",
    photo : "",
    description : "",
    leaflet : "",
    manufName : "",
    batchSpecificVersion : false,
    reportURL : "adverseEventReportingURL",
    antiCounterfeitingURL : "acfProductCheckURL",
    adverseEventsReportingEnabled : "flagEnableAdverseEventReporting",
    antiCounterfeitingEnabled : "flagEnableACFProductCheck",
    showEPIOnBatchRecalled : "flagDisplayEPI_BatchRecalled",
    showEPIOnSNRecalled : "flagDisplayEPI_SNRecalled",
    showEPIOnSNDecommissioned : "flagDisplayEPI_SNDecommissioned",
    showEPIOnSNUnknown : "flagDisplayEPI_SNUnknown",
    showEPIOnIncorrectExpiryDate : "flagDisplayEPI_EXPIncorrect",
    showEPIOnBatchExpired : "flagDisplayEPI_BatchExpired",
    practitionerInfo : "healthcarePractitionerInfo",
    patientLeafletInfo : "patientSpecificLeaflet",
    markets:"markets",
    internalMaterialCode:"internalMaterialCode",
    inventedName:"inventedName",
    strength:"strength"
};

module.exports.constants = {
    'PACKAGES_STORAGE_PATH': "/app/data/packages.json",
        'DATA_STORAGE_PATH': "/app/data",
        'PRODUCTS_TABLE': "products",
        'LAST_VERSION_PRODUCTS_TABLE': "last_version_products",
        'LOGS_TABLE': "logs",
        'SERIAL_NUMBERS_LOGS_TABLE': "serial_numbers_logs",
        'PRODUCT_KEYSSI_STORAGE_TABLE': "productKeySSIs",
        'BATCHES_STORAGE_TABLE': "batches",
        'PRODUCT_DSU_MOUNT_POINT': "/gtinDSU",
        'BATCH_STORAGE_FILE': "/batch.json",
        'PRODUCT_STORAGE_FILE': "/product.json",
        'PRODUCT_IMAGE_FILE': "/image.png",
        'LEAFLET_ATTACHMENT_FILE': "/leaflet.xml",
        'SMPC_ATTACHMENT_FILE': "/smpc.xml"
};
